spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor_microservice_db?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-password: 
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15    
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   